## ----------------------------------------------------------------------------

# Amazon : all services
export ACCESS_KEY_ID=...
export SECRET_ACCESS_KEY=...
export AWS_ACCOUNT_ID=...
export CANONICAL_USER_ID=...

## ----------------------------------------------------------------------------
